[project]
name = "notesapi"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "yaisnw", email = "wafazadayasin@gmail.com" }
]
requires-python = ">=3.10"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "psycopg2-binary>=2.9.13",
    "sqlmodel>=0.0.42",
]

[project.scripts]
notesapi = "notesapi:main"

[build-system]
requires = ["uv_build>=0.12.13,<0.13.0"]
build-backend = "uv_build"
